CarClass carObj1 = new CarClass();

carObj1.carColor = 'blue';
carObj1.carSpeed = 180;
carObj1.hasSunrrof = true; 

// system.debug(carObj1);
// system.debug(carObj1.carColor);
// system.debug(carObj1.carSpeed);
// system.debug(carObj1.hasSunrrof);

// carObj1.startEngine();
// carObj1.stopEngine();

CarClass carObj2 = new CarClass();
carObj2.carColor = 'red';

system.debug(carObj2);
system.debug(carObj1);